import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { NavBar, Phone, PrimaryButton, StatusBar } from "@/components/chrome/Chrome";

const TOPICS = [
  "Top up",
  "Withdraw money",
  "Scam/Phising",
  "Account",
  "Transaction Issue",
  "Fraud & security",
  "Product & services",
  "Other",
];

const ISSUES = [
  "I need to update my e-KTP data",
  "Issues with Bank transfer or e-wallet",
  "Issues with GoPay Later transaction",
  "My issue is not listed here",
];

export function HelpScreen() {
  const navigate = useNavigate();
  return (
    <Phone>
      <StatusBar />
      <NavBar title="Help" onBack={() => navigate(-1)} />
      <div className="flex-1 overflow-y-auto px-4 pb-6">
        <h2 className="text-[18px] font-semibold">Any relevant issues?</h2>
        <ul className="mt-3 overflow-hidden rounded-[20px] bg-card">
          {ISSUES.map((issue) => (
            <li key={issue} className="border-b border-line last:border-b-0">
              <button
                type="button"
                className="w-full px-4 py-3.5 text-left text-[14px]"
                onClick={() =>
                  issue.startsWith("I need to update") ? navigate("/review") : navigate("/dira")
                }
              >
                {issue}
              </button>
            </li>
          ))}
        </ul>
        <h3 className="mt-6 text-[16px] font-semibold">All topics</h3>
        <div className="mt-3 grid grid-cols-2 gap-2">
          {TOPICS.map((topic) => (
            <button
              key={topic}
              type="button"
              className="rounded-2xl bg-card px-3 py-4 text-left text-[13px] font-semibold"
              onClick={() => navigate("/dira")}
            >
              {topic}
            </button>
          ))}
        </div>
      </div>
    </Phone>
  );
}

const DIRA_REPLY =
  "You can update your e-KTP yourself. Make sure it’s the most updated card, then I’ll take you to the data check.";

export function DiraScreen() {
  const navigate = useNavigate();
  const [sent, setSent] = useState(false);
  return (
    <Phone>
      <StatusBar />
      <NavBar title="Dira" onBack={() => navigate(-1)} />
      <div className="flex flex-1 flex-col px-4 pb-4">
        <div className="flex-1 space-y-3 overflow-y-auto">
          <p className="ml-auto max-w-[80%] rounded-2xl bg-gopay px-3 py-2 text-[14px] text-white">
            I need to update my KTP data
          </p>
          {sent ? (
            <div className="max-w-[85%] rounded-2xl bg-card px-3 py-3 text-[14px] leading-5 text-ink">
              <p>{DIRA_REPLY}</p>
              <button
                type="button"
                className="mt-3 w-full rounded-full bg-gopay py-2 text-[14px] font-bold text-white"
                onClick={() => navigate("/review")}
              >
                Update your e-KTP data
              </button>
            </div>
          ) : null}
        </div>
        <PrimaryButton onClick={() => setSent(true)} disabled={sent}>
          {sent ? "Dira replied" : "Ask Dira"}
        </PrimaryButton>
      </div>
    </Phone>
  );
}

export function LegalScreen({ kind }: { kind: "terms" | "privacy" }) {
  const navigate = useNavigate();
  const title = kind === "terms" ? "Terms & Conditions" : "Privacy Policy";
  return (
    <Phone>
      <StatusBar />
      <NavBar title={title} onBack={() => navigate(-1)} />
      <div className="flex-1 overflow-y-auto px-4 pb-6 text-[14px] leading-6 text-body">
        <p>
          This is demo copy for the GoPay reKYC flow. Identity data stays in this browser and is
          used only to show how an update is stored as a new submission.
        </p>
        <p className="mt-3">
          GoPay is supervised by Bank Indonesia. An electronic certificate may be generated by
          DigiSign after a successful update.
        </p>
      </div>
    </Phone>
  );
}
