import type { FlowNode } from "./types";

export const accountNodes: FlowNode[] = [
  {
    id: "account",
    topic: "account",
    title: "My account & plan",
    say: "Sure. What would you like to update?",
    options: [
      { label: "Update my mailing address", next: "account.address" },
      { label: "Add a concession card", next: "account.concession" },
      { label: "Is there a better plan for me?", next: "account.plan" },
      { label: "Help logging in", next: "account.login" },
      { label: "Close my account", next: "moving.disconnect" },
    ],
    keywords: ["my account", "account details", "update my details", "change my details", "plan details", "profile"],
  },
  {
    id: "account.address",
    topic: "account",
    title: "Mailing address",
    say: "Your bills currently go to {mailingAddress}. What's the new mailing address?",
    card: { kind: "form", form: "mailing-address", next: "account.address.done" },
    options: [{ label: "Keep it as it is", next: "resolved" }],
    keywords: ["mailing address", "postal address", "change address", "update address", "where my bills go"],
  },
  {
    id: "account.address.done",
    topic: "account",
    title: "Address updated",
    say: "Done. From now on, letters and paper bills will go to {newMailingAddress}. Your supply address hasn't changed.",
    card: { kind: "success", title: "Mailing address updated", detail: "{newMailingAddress}" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account.concession",
    topic: "account",
    title: "Concession card",
    say: "Let's make sure you're getting every concession you're entitled to. Which card do you have, and what's the card number?",
    card: { kind: "form", form: "concession", next: "account.concession.done" },
    options: [{ label: "Which cards are eligible?", next: "support.rebates" }],
    keywords: ["concession", "concession card", "pension card", "pensioner", "health care card", "seniors card", "dva"],
  },
  {
    id: "account.concession.done",
    topic: "account",
    title: "Concession added",
    say: "Thanks. I've added your {concessionType}. Once Services Australia confirms it, usually within 2 days, the concession will apply to your electricity and gas bills.",
    card: { kind: "success", title: "Concession submitted", detail: "{concessionType} · Verifying with Services Australia" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account.plan",
    topic: "account",
    title: "Better plan",
    say: "Based on your last 12 months, you're already on our lowest priced plan for your usage, Value Saver. The Netflix Plan costs about 17 dollars more a year but includes Netflix Standard with ads.",
    card: { kind: "plan-compare" },
    options: [
      { label: "Switch me to the Netflix Plan", next: "account.plan.done" },
      { label: "I'll stay on Value Saver", next: "resolved" },
      { label: "What about solar plans?", next: "solar.fit" },
    ],
    keywords: ["better plan", "cheaper plan", "change plan", "switch plan", "best plan", "compare plans", "save money"],
  },
  {
    id: "account.plan.done",
    topic: "account",
    title: "Plan switched",
    say: "Done. You'll move to the Netflix Plan from your next billing period. We'll email your Netflix activation link today.",
    card: { kind: "success", title: "Plan change confirmed", detail: "Netflix Plan · From 23 September billing period · No exit fees" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account.login",
    topic: "account",
    title: "Login help",
    say: "Let's get you back in. Most login issues are fixed by resetting your password. You can also turn on two-factor authentication or create a passkey for faster, safer sign in.",
    card: {
      kind: "steps",
      title: "Login help",
      steps: ["Select 'Forgot password' on the log in page", "Check {email} for a reset link (valid 30 minutes)", "Turn on 2FA or add a passkey in Profile › Security"],
    },
    options: [
      { label: "Send me a reset link", next: "account.login.done" },
      { label: "I think I've been scammed", next: "handoff" },
    ],
    keywords: ["log in", "login", "password", "forgot password", "can't log in", "locked out", "2fa", "passkey", "two factor"],
  },
  {
    id: "account.login.done",
    topic: "account",
    title: "Reset link sent",
    say: "I've sent a password reset link to {email}. It's valid for 30 minutes.",
    card: { kind: "success", title: "Reset link sent", detail: "{email} · Expires in 30 minutes" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
];
