import type { FlowNode } from "./types";

export const billingNodes: FlowNode[] = [
  {
    id: "billing",
    topic: "billing",
    title: "Billing & payments",
    say: "Sure, let's sort out your bill. What do you need help with?",
    options: [
      { label: "Pay my bill", next: "billing.pay" },
      { label: "My bill is higher than expected", next: "billing.high" },
      { label: "Understand my bill", next: "billing.understand" },
      { label: "Set up direct debit", next: "billing.directdebit" },
      { label: "Request a credit refund", next: "billing.refund" },
      { label: "I need more time to pay", next: "support.extension" },
    ],
    keywords: ["bill", "billing", "invoice", "payment", "account balance", "how much do i owe"],
  },
  {
    id: "billing.pay",
    topic: "billing",
    title: "Pay my bill",
    say: "Your latest electricity bill is {elecAmount}, due {elecDue}. Your gas bill of {gasAmount} is due {gasDue}. How would you like to pay?",
    card: { kind: "bill", billKind: "electricity" },
    options: [
      { label: "Pay now with my saved card", next: "billing.pay.card" },
      { label: "Show BPAY details", next: "billing.pay.bpay" },
      { label: "Other ways to pay", next: "billing.pay.other" },
      { label: "I can't pay it all right now", next: "support" },
    ],
    keywords: ["pay my bill", "pay bill", "make a payment", "pay now", "pay electricity", "pay gas", "pay the bill"],
  },
  {
    id: "billing.pay.card",
    topic: "billing",
    title: "Pay with saved card",
    say: "I'll pay {elecAmount} using your {card}. Shall I go ahead?",
    card: { kind: "payment-confirm" },
    options: [
      { label: "Yes, pay {elecAmount}", next: "billing.pay.done" },
      { label: "Pay both bills ({totalDue})", next: "billing.pay.done", set: { paidAmount: "{totalDue}" } },
      { label: "Not now", next: "billing" },
    ],
    keywords: ["saved card", "pay with card", "credit card", "visa"],
  },
  {
    id: "billing.pay.done",
    topic: "billing",
    title: "Payment made",
    say: "Done. Your payment of {paidAmount} has gone through and your receipt number is {receipt}. It'll show in My Account within a few minutes.",
    card: { kind: "success", title: "Payment successful", detail: "{paidAmount} paid with {card} · Receipt {receipt}" },
    options: [
      { label: "Set up direct debit so I don't forget", next: "billing.directdebit" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "billing.pay.bpay",
    topic: "billing",
    title: "BPAY details",
    say: "Here are your BPAY details. Use biller code 2345 and your reference number from the card. Payments can take up to two business days to reach us.",
    card: { kind: "bpay" },
    options: [
      { label: "Pay with my card instead", next: "billing.pay.card" },
      { label: "Got it, thanks", next: "resolved" },
    ],
    keywords: ["bpay", "biller code", "reference number"],
  },
  {
    id: "billing.pay.other",
    topic: "billing",
    title: "Ways to pay",
    say: "There are plenty of ways to pay. The quickest is the AGL app or direct debit, but you can also use PayPal, BPAY, SMS Pay, Centrepay or Australia Post.",
    card: {
      kind: "steps",
      title: "Ways to pay",
      steps: [
        "AGL app — one-touch payment with your stored card",
        "Direct Debit — automatic, never miss a due date",
        "Online with card or PayPal",
        "BPAY® — biller code 2345",
        "SMS Pay — reply 'Pay' to our reminder text",
        "Centrepay, Australia Post or the AGL Payment line",
      ],
    },
    options: [
      { label: "Pay now with my saved card", next: "billing.pay.card" },
      { label: "Set up direct debit", next: "billing.directdebit" },
      { label: "Thanks, that helps", next: "resolved" },
    ],
    keywords: ["ways to pay", "payment options", "paypal", "centrepay", "australia post", "sms pay"],
  },
  {
    id: "billing.high",
    topic: "billing",
    title: "Higher bill than expected",
    say: "Let's work out why. Your latest electricity bill used {elecKwh}, which is {usageChange} compared with the same time last year. Has anything changed at home?",
    card: { kind: "usage-compare" },
    options: [
      { label: "It's been cold, heater's been on", next: "billing.high.seasonal" },
      { label: "More people home or new appliances", next: "billing.high.usage" },
      { label: "I think the bill was estimated", next: "meters.estimated" },
      { label: "Nothing's changed", next: "billing.high.unchanged" },
    ],
    keywords: [
      "bill is high",
      "high bill",
      "bill too high",
      "bill so high",
      "bill higher",
      "expensive",
      "bill went up",
      "bill has gone up",
      "unexpected bill",
      "why is my bill",
      "bill shock",
    ],
  },
  {
    id: "billing.high.seasonal",
    topic: "billing",
    title: "Seasonal usage",
    say: "That'll be it. Winter heating is usually the biggest driver of a higher bill. Your heaviest days were weekends, when the house was busiest. Here are a few quick ways to bring it down.",
    card: {
      kind: "steps",
      title: "Easy winter savings",
      steps: [
        "Set reverse-cycle heating to 18–20°C — each degree adds up to 10%",
        "Close doors to heat only the rooms you're using",
        "Use a budget alert in the AGL app to track spend weekly",
        "Consider Bill Smoothing to spread costs evenly across the year",
      ],
    },
    options: [
      { label: "I need more time to pay this one", next: "support.extension" },
      { label: "Is there a better plan for me?", next: "account.plan" },
      { label: "That makes sense, thanks", next: "resolved" },
    ],
    keywords: ["heater", "heating", "cold", "winter", "air conditioning", "cooling", "summer"],
  },
  {
    id: "billing.high.usage",
    topic: "billing",
    title: "Household changes",
    say: "Extra people at home or new appliances like a dryer or a second fridge can add up quickly. The AGL app shows your usage by hour, so you can see exactly when the spikes happen.",
    card: {
      kind: "steps",
      title: "Find what's using power",
      steps: [
        "Open the AGL app › Usage › Hourly to spot spikes",
        "Switch off second fridges and appliances on standby",
        "Run dryers and dishwashers in off-peak times",
      ],
    },
    options: [
      { label: "Is there a better plan for me?", next: "account.plan" },
      { label: "I need more time to pay", next: "support.extension" },
      { label: "Thanks", next: "resolved" },
    ],
    keywords: ["new appliance", "more people", "working from home", "pool pump"],
  },
  {
    id: "billing.high.unchanged",
    topic: "billing",
    title: "Nothing changed",
    say: "Thanks. Your bill used an actual meter read and your rates changed on 1 July, which explains part of the increase. If it still doesn't look right, I can get someone to review it with you.",
    card: {
      kind: "info",
      title: "What changed on 1 July",
      body: "Network and wholesale costs rose across NSW this year. Your usage rate moved from 22.9c to 24.15c per kWh.",
    },
    options: [
      { label: "Get someone to review my bill", next: "handoff" },
      { label: "Is there a better plan for me?", next: "account.plan" },
      { label: "Okay, thanks", next: "resolved" },
    ],
  },
  {
    id: "billing.understand",
    topic: "billing",
    title: "Understand my bill",
    say: "Happy to walk you through it. Which part would you like explained?",
    options: [
      { label: "Supply and usage charges", next: "billing.understand.charges" },
      { label: "Estimated or actual reads", next: "meters.estimated" },
      { label: "Energy Bill Relief credit", next: "support.rebates" },
      { label: "Something else on my bill", next: "handoff" },
    ],
    keywords: ["understand my bill", "explain my bill", "read my bill", "what is on my bill", "charges on my bill"],
  },
  {
    id: "billing.understand.charges",
    topic: "billing",
    title: "Supply and usage charges",
    say: "Your bill has two main parts. The supply charge is a fixed daily amount for being connected, which is 98 cents a day on Value Saver. The usage charge is what you used, at 24.15 cents per kilowatt hour.",
    card: {
      kind: "steps",
      title: "Your electricity rates (Value Saver, Ausgrid)",
      steps: ["Supply charge: 98.21c per day", "Usage: 24.15c per kWh", "Solar feed-in: 2.0c per kWh", "All prices include GST"],
    },
    options: [
      { label: "Is there a better plan for me?", next: "account.plan" },
      { label: "Thanks, that's clear", next: "resolved" },
    ],
    keywords: ["supply charge", "usage charge", "daily charge", "rates", "kwh rate", "tariff"],
  },
  {
    id: "billing.directdebit",
    topic: "billing",
    title: "Direct debit",
    say: "Direct debit pays your bill automatically on the due date, so you'll never miss one. I can set it up with your {bankAccount}. Would you like me to?",
    options: [
      { label: "Yes, set it up", next: "billing.directdebit.done" },
      { label: "Use my {card} instead", next: "billing.directdebit.done", set: { debitMethod: "{card}" } },
      { label: "Not right now", next: "resolved" },
    ],
    keywords: ["direct debit", "automatic payment", "auto pay", "autopay", "pay automatically"],
  },
  {
    id: "billing.directdebit.done",
    topic: "billing",
    title: "Direct debit set up",
    say: "All set. Direct debit is on for electricity and gas using {debitMethod}. We'll remind you a few days before each payment.",
    card: { kind: "success", title: "Direct debit active", detail: "Electricity and gas · {debitMethod} · Starts next bill" },
    options: [{ label: "Great, thanks", next: "resolved" }],
  },
  {
    id: "billing.refund",
    topic: "billing",
    title: "Credit refund",
    say: "Your gas account is in credit by {gasCredit}. I can refund it to your nominated bank account, or move it to your electricity account.",
    card: { kind: "refund" },
    options: [
      { label: "Refund to my bank account", next: "billing.refund.done", set: { refundTarget: "your {bankAccount}" } },
      { label: "Move it to my electricity bill", next: "billing.refund.done", set: { refundTarget: "your electricity account" } },
      { label: "Leave it for now", next: "resolved" },
    ],
    keywords: ["refund", "credit refund", "in credit", "money back", "overpaid"],
  },
  {
    id: "billing.refund.done",
    topic: "billing",
    title: "Refund requested",
    say: "Done. {gasCredit} is on its way to {refundTarget}. Refunds usually arrive within 5 business days.",
    card: { kind: "success", title: "Refund requested", detail: "{gasCredit} → {refundTarget} · 3–5 business days" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
];
