import type { FlowNode } from "./types";

export const internetMobileNodes: FlowNode[] = [
  {
    id: "netmob",
    topic: "internet-mobile",
    title: "Internet & mobile",
    say: "Happy to help with your internet or mobile. What's going on?",
    options: [
      { label: "My internet isn't working", next: "internet.down" },
      { label: "Slow speeds or drop-outs", next: "internet.slow" },
      { label: "Check for nbn® outages", next: "internet.outage" },
      { label: "My phone has no signal", next: "mobile.signal" },
      { label: "Mobile data isn't working", next: "mobile.data" },
      { label: "Travelling overseas", next: "mobile.roaming" },
      { label: "Check my data usage", next: "mobile.usage" },
    ],
    keywords: ["internet", "nbn", "wifi", "wi-fi", "modem", "mobile", "sim", "phone plan", "broadband"],
  },
  {
    id: "internet.down",
    topic: "internet-mobile",
    title: "Internet not working",
    say: "Sorry your internet's down. I've checked {shortAddress} and there are no nbn outages reported right now, so let's try three quick steps. Tell me how you go.",
    card: {
      kind: "steps",
      title: "Get back online",
      steps: [
        "Check Wi-Fi is turned on for your device and the modem's lights are on",
        "Turn your modem off at the wall, wait 30 seconds, then turn it back on",
        "Reset the nbn® connection box — power it off for 30 seconds and check the cables are secure",
      ],
    },
    options: [
      { label: "That fixed it", next: "resolved" },
      { label: "Still not working", next: "internet.down.linetest" },
      { label: "The modem lights are red", next: "internet.down.linetest" },
    ],
    keywords: [
      "internet not working",
      "internet isn't working",
      "internet is down",
      "internet down",
      "no internet",
      "can't connect",
      "cannot connect",
      "wifi not working",
      "wi-fi not working",
      "wifi down",
      "offline",
      "no connection",
    ],
  },
  {
    id: "internet.down.linetest",
    topic: "internet-mobile",
    title: "Line test",
    say: "Thanks for trying those. I've run a remote line test on your FTTP connection and it can't see your modem, which usually means a fault on the line. The best next step is for our internet team to book an nbn technician.",
    card: {
      kind: "info",
      title: "Line test result",
      body: "nbn® FTTP · Connection box online · Modem not detected · Test ID LT-88213",
    },
    options: [
      { label: "Connect me to the internet team", next: "handoff" },
      { label: "Set up a 4G backup on my phone", next: "internet.hotspot" },
    ],
  },
  {
    id: "internet.hotspot",
    topic: "internet-mobile",
    title: "Mobile hotspot",
    say: "Good idea. You can use your phone as a hotspot while we fix it. I've added 20 gigabytes of free bonus data to {mobileNumber} for the next 7 days.",
    card: { kind: "success", title: "Bonus data added", detail: "20GB on {mobileNumber} · Expires in 7 days" },
    options: [
      { label: "Now connect me to the internet team", next: "handoff" },
      { label: "Thanks", next: "resolved" },
    ],
    keywords: ["hotspot", "backup internet", "tether"],
  },
  {
    id: "internet.slow",
    topic: "internet-mobile",
    title: "Slow speeds",
    say: "Slow speeds are frustrating. You're on {nbnPlan}, which typically gets about 94 megabits in the evening. Let's run a quick speed test from your modem.",
    card: { kind: "speed-test" },
    options: [
      { label: "Show me how to do an isolation test", next: "internet.isolation" },
      { label: "It's still slow", next: "handoff" },
      { label: "Could I get a faster plan?", next: "internet.upgrade" },
    ],
    keywords: ["slow", "slow internet", "speed", "drop out", "dropping out", "drop-outs", "buffering", "lag", "keeps disconnecting"],
  },
  {
    id: "internet.isolation",
    topic: "internet-mobile",
    title: "Isolation test",
    say: "An isolation test checks whether another device is causing the problem. Disconnect everything except the modem, wait 10 to 15 minutes, then test again with a cable.",
    card: {
      kind: "steps",
      title: "Isolation test",
      steps: [
        "Disconnect every device from the modem except one laptop",
        "Unplug phones, filters and extra cables from the wall sockets",
        "Wait 10–15 minutes, then run a wired speed test",
        "Plug devices back in one at a time to find the culprit",
      ],
    },
    options: [
      { label: "Found it, all good now", next: "resolved" },
      { label: "Still slow", next: "handoff" },
    ],
    keywords: ["isolation test"],
  },
  {
    id: "internet.upgrade",
    topic: "internet-mobile",
    title: "Faster plan",
    say: "Good news. Your FTTP connection can get Home Fast Fibre, nbn 500, for the same {nbnPrice} a month you pay now with your energy discount.",
    card: {
      kind: "info",
      title: "Home Fast Fibre · nbn® 500",
      body: "Typical evening speed 500 Mbps · $95/mth with AGL energy · No lock-in contract",
      link: { label: "Compare nbn® plans", to: "/internet" },
    },
    options: [
      { label: "Upgrade me", next: "internet.upgrade.done" },
      { label: "Maybe later", next: "resolved" },
    ],
    keywords: ["faster plan", "upgrade internet", "faster internet", "fibre upgrade"],
  },
  {
    id: "internet.upgrade.done",
    topic: "internet-mobile",
    title: "Plan upgraded",
    say: "Done. You'll move to Home Fast Fibre within 24 hours, with no change to your bill. Restart your modem tomorrow to pick up the new speed.",
    card: { kind: "success", title: "Upgrade requested", detail: "Home Fast Fibre nbn® 500 · $95/mth · Active within 24 hours" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "internet.outage",
    topic: "internet-mobile",
    title: "nbn® outages",
    say: "There are no current nbn outages at {shortAddress}. There's planned maintenance on 2 October between midnight and 6am, which may interrupt your service briefly.",
    card: { kind: "outage-status", service: "nbn" },
    options: [
      { label: "My internet is still down", next: "internet.down" },
      { label: "Check mobile network status", next: "mobile.signal" },
      { label: "Thanks", next: "resolved" },
    ],
    keywords: ["outage", "nbn outage", "network status", "maintenance", "is there an outage"],
  },
  {
    id: "mobile.signal",
    topic: "internet-mobile",
    title: "No mobile signal",
    say: "Let's get your phone reconnected. AGL mobile uses the Optus network and there are no outages near {shortAddress}. Try restarting your phone and reseating the SIM.",
    card: {
      kind: "steps",
      title: "Reconnect your phone",
      steps: [
        "Turn the phone off by holding the power button",
        "Open the SIM tray, remove the SIM and wipe it with a dry cloth",
        "Reinsert the SIM, turn the phone on and wait 1–2 minutes",
      ],
    },
    options: [
      { label: "That fixed it", next: "resolved" },
      { label: "Calls work but data doesn't", next: "mobile.data" },
      { label: "Still no signal", next: "handoff" },
    ],
    keywords: ["no signal", "no service", "no reception", "sos only", "can't make calls", "phone not working", "mobile not working"],
  },
  {
    id: "mobile.data",
    topic: "internet-mobile",
    title: "Mobile data",
    say: "Usually your phone sets up data automatically, but sometimes the APN needs to be entered. What kind of phone do you have?",
    options: [
      { label: "iPhone", next: "mobile.data.iphone" },
      { label: "Android", next: "mobile.data.android" },
    ],
    keywords: ["mobile data", "data not working", "apn", "4g not working", "5g not working"],
  },
  {
    id: "mobile.data.iphone",
    topic: "internet-mobile",
    title: "iPhone APN",
    say: "On your iPhone, go to Settings, Mobile, Mobile Data Options, Mobile Data Network. Set the APN to yes internet, all one word, then restart your phone.",
    card: {
      kind: "steps",
      title: "iPhone APN settings",
      steps: ["Settings › Mobile › Mobile Data Options › Mobile Data Network", "APN: yesinternet", "Restart and wait 1–2 minutes before testing"],
    },
    options: [
      { label: "Data's working now", next: "resolved" },
      { label: "Still not working", next: "handoff" },
    ],
  },
  {
    id: "mobile.data.android",
    topic: "internet-mobile",
    title: "Android APN",
    say: "On Android, open your Access Point Names settings and add a new APN called AGL Phone Internet, with the APN yes internet. Save it, select it, then restart.",
    card: {
      kind: "steps",
      title: "Android APN settings",
      steps: [
        "Settings › Mobile networks › Access Point Names › Add",
        "Name: AGL Phone Internet · APN: yesinternet",
        "MCC 505 · MNC 02 · Authentication PAP · APN type default",
        "Save, select the new APN and restart",
      ],
    },
    options: [
      { label: "Data's working now", next: "resolved" },
      { label: "Still not working", next: "handoff" },
    ],
  },
  {
    id: "mobile.roaming",
    topic: "internet-mobile",
    title: "Travelling overseas",
    say: "Our 5 dollar a day travel pass is already switched on for {mobileNumber}. It gives you 5 gigabytes of data plus unlimited calls and texts in over 100 countries, and you only pay on days you use it.",
    card: {
      kind: "info",
      title: "$5/day international roaming",
      body: "5GB data · Unlimited calls & texts · 100+ countries · Charged only on days you use your phone overseas",
    },
    options: [
      { label: "Turn roaming off", next: "mobile.roaming.off" },
      { label: "Great, thanks", next: "resolved" },
    ],
    keywords: ["roaming", "overseas", "travel", "travelling", "international", "holiday"],
  },
  {
    id: "mobile.roaming.off",
    topic: "internet-mobile",
    title: "Roaming off",
    say: "Done, international roaming is now off. You can turn it back on any time in the AGL app.",
    card: { kind: "success", title: "Roaming turned off", detail: "{mobileNumber} · Change any time in the AGL app" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "mobile.usage",
    topic: "internet-mobile",
    title: "Data usage",
    say: "You've used {dataUsed} of your {dataAllowance} this month, with 14 days to go. You're well on track, and unused data rolls over.",
    card: {
      kind: "info",
      title: "Medium 80GB SIM · {mobileNumber}",
      body: "{dataUsed} used of {dataAllowance} · 14 days left · Rollover up to 200GB",
    },
    options: [
      { label: "Could I save with a smaller plan?", next: "account.plan" },
      { label: "Thanks", next: "resolved" },
    ],
    keywords: ["data usage", "how much data", "data left", "used my data"],
  },
];
