import type { FlowNode } from "./types";

const ACCESSIBLE_LINE = { label: "Accessible Bookings", phone: "1300 665 915", note: "Mon–Fri 9am–5pm AEST" };

export const helpNodes: FlowNode[] = [
  {
    id: "accessible",
    topic: "accessibility",
    title: "Accessible bookings",
    say: "I can help with wheelchair seating, easy-access seats and Companion Card bookings. What do you need?",
    options: [
      { label: "Book wheelchair or easy-access seating", next: "accessible.form" },
      { label: "Companion Card", next: "accessible.companion" },
      { label: "Access at the venue", next: "eventday" },
      { label: "Call the Accessible Bookings line", next: "accessible.call" },
    ],
    keywords: ["wheelchair", "accessible", "accessibility", "companion card", "disability", "mobility", "hearing", "vision impaired", "carer", "easy access"],
  },
  {
    id: "accessible.companion",
    topic: "accessibility",
    title: "Companion Card",
    say: "If you hold a Companion Card, your companion's ticket is free at participating events.",
    card: {
      kind: "steps",
      title: "Booking with a Companion Card",
      steps: [
        "Choose your seats as normal, then pick the Companion Card price type for the second ticket.",
        "Add your Companion Card number at checkout.",
        "Bring the card to the venue — it may be checked at entry.",
      ],
    },
    options: [
      { label: "Book with help", next: "accessible.form" },
      { label: "Thanks", next: "resolved" },
    ],
  },
  {
    id: "accessible.form",
    topic: "accessibility",
    title: "Accessible booking request",
    say: "Tell me the event and what you need, and our Accessibility team will hold the right seats and call you back.",
    card: { kind: "form", form: "accessible-booking", next: "accessible.done" },
    options: [{ label: "Call instead", next: "accessible.call" }],
  },
  {
    id: "accessible.done",
    topic: "accessibility",
    title: "Request logged",
    say: "Thanks {firstName}. I've sent your request for {accessEvent} to the Accessibility team with reference {requestRef}. They'll call you within one business day to confirm seats.",
    card: { kind: "success", title: "Accessible booking request sent", detail: "{accessNeed} · {accessQuantity} · ref {requestRef}" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "accessible.call",
    topic: "accessibility",
    title: "Accessible Bookings line",
    say: "You can reach our Accessible Bookings team on 1300 665 915, Monday to Friday, 9am to 5pm AEST.",
    card: { kind: "contact", title: "Accessible Bookings", entries: [ACCESSIBLE_LINE, { label: "National Relay Service", phone: "133 677", note: "Then ask for 1300 665 915" }] },
    options: [{ label: "Back to topics", next: "menu" }],
  },
  {
    id: "groups",
    topic: "groups",
    title: "Group bookings",
    say: "Groups of 10 or more can get group pricing and seats together for selected shows. Want me to send an enquiry to the Groups team?",
    options: [
      { label: "Make a group enquiry", next: "groups.form" },
      { label: "School or corporate groups", next: "groups.school" },
      { label: "Back to topics", next: "menu" },
    ],
    keywords: ["group booking", "group of", "groups", "school group", "corporate", "bulk tickets", "big group"],
  },
  {
    id: "groups.school",
    topic: "groups",
    title: "School & corporate",
    say: "Schools get teacher tickets and invoicing on selected theatre shows, and corporate groups can add hospitality. The Groups team will tailor it.",
    options: [
      { label: "Make a group enquiry", next: "groups.form" },
      { label: "Thanks", next: "resolved" },
    ],
  },
  {
    id: "groups.form",
    topic: "groups",
    title: "Group enquiry",
    say: "Which event, how many people, and when would you like to go?",
    card: { kind: "form", form: "group-enquiry", next: "groups.done" },
    options: [{ label: "Back", next: "groups" }],
  },
  {
    id: "groups.done",
    topic: "groups",
    title: "Enquiry sent",
    say: "Sent! The Groups team will email {email} with options for {groupSize} people at {groupEvent} within two business days.",
    card: { kind: "success", title: "Group enquiry sent", detail: "{groupSize} people · {groupEvent} · {groupDate}" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "payments",
    topic: "payments",
    title: "Payments & vouchers",
    say: "What's the payment question?",
    options: [
      { label: "I've been charged twice", next: "payments.double" },
      { label: "My payment was declined", next: "payments.declined" },
      { label: "Booking and service fees", next: "payments.fees" },
      { label: "Afterpay", next: "payments.afterpay" },
      { label: "Gift vouchers", next: "vouchers" },
    ],
    keywords: ["payment", "charged", "charge", "declined", "credit card", "fees", "fee", "afterpay", "pay later"],
  },
  {
    id: "payments.double",
    topic: "payments",
    title: "Charged twice",
    say: "Usually one of the charges is a pending hold from a checkout that timed out. Holds drop off by themselves within 3 to 5 business days and only one order shows in your account.",
    options: [
      { label: "Both charges have settled", next: "handoff" },
      { label: "Okay, I'll wait", next: "resolved" },
    ],
    keywords: ["charged twice", "double charged", "two charges", "charged two times"],
  },
  {
    id: "payments.declined",
    topic: "payments",
    title: "Payment declined",
    say: "Declines usually come from the bank's fraud checks. Here's what fixes it most of the time.",
    card: {
      kind: "steps",
      title: "If your payment is declined",
      steps: ["Check the card's expiry, CVV and billing postcode.", "Approve the purchase in your banking app if prompted.", "Try another card or PayPal — your seats are held until the timer runs out."],
    },
    options: [
      { label: "Still declined", next: "handoff" },
      { label: "That worked", next: "resolved" },
    ],
  },
  {
    id: "payments.fees",
    topic: "payments",
    title: "Fees",
    say: "Ticket prices include GST. Each ticket has a service fee, each order a handling fee of $6.95, and posted souvenir tickets cost $8.50. Every fee shows before you pay.",
    options: [{ label: "Thanks", next: "resolved" }],
    keywords: ["booking fee", "service fee", "handling fee", "why the fees"],
  },
  {
    id: "payments.afterpay",
    topic: "payments",
    title: "Afterpay",
    say: "Afterpay is available on most events — pay in four instalments, interest-free. Choose it at the payment step. Refunds for cancelled events go back to your Afterpay account.",
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "vouchers",
    topic: "payments",
    title: "Gift vouchers",
    say: "Ticketek Gift Vouchers work on any event and last three years. Want to check a balance or buy one?",
    options: [
      { label: "Check my balance", next: "vouchers.form" },
      { label: "Buy a gift voucher", next: "vouchers.buy" },
    ],
    keywords: ["gift voucher", "gift card", "voucher balance", "voucher"],
  },
  {
    id: "vouchers.form",
    topic: "payments",
    title: "Voucher balance",
    say: "What's the voucher code? It's on the voucher email, starting with GV.",
    card: { kind: "form", form: "voucher-balance", next: "vouchers.balance" },
    options: [{ label: "Back", next: "vouchers" }],
  },
  {
    id: "vouchers.balance",
    topic: "payments",
    title: "Voucher balance",
    say: "Voucher {voucherCode} has {voucherBalance} left to spend on any event.",
    card: { kind: "success", title: "Voucher balance", detail: "{voucherCode}: {voucherBalance}" },
    options: [
      { label: "Find something to see", next: "discover.recs" },
      { label: "Thanks", next: "resolved" },
    ],
  },
  {
    id: "vouchers.buy",
    topic: "payments",
    title: "Buy a voucher",
    say: "You can buy a voucher from $20 to $500, delivered by email instantly or on a date you choose.",
    card: { kind: "info", title: "Ticketek Gift Vouchers", body: "The gift of live — for any event on Ticketek.", link: { label: "Buy a gift voucher", to: "/gift-vouchers" } },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account",
    topic: "account",
    title: "Account & privacy",
    say: "What would you like to do with your account?",
    options: [
      { label: "I can't sign in", next: "account.signin" },
      { label: "Update my details", next: "account.details" },
      { label: "Unsubscribe from marketing", next: "account.unsubscribe" },
      { label: "Delete my data", next: "account.erasure" },
      { label: "Close my account", next: "account.close" },
    ],
    keywords: ["account", "password", "forgot password", "can't sign in", "cant log in", "update my details", "change my email", "privacy"],
  },
  {
    id: "account.signin",
    topic: "account",
    title: "Can't sign in",
    say: "Let's reset your password. It takes a minute.",
    card: {
      kind: "steps",
      title: "Reset your password",
      steps: ["Go to Sign In and choose Forgot password.", "Enter {email} and we'll email a reset link, valid for 1 hour.", "Choose a new password with at least 8 characters."],
    },
    options: [
      { label: "That worked", next: "resolved" },
      { label: "I don't get the email", next: "handoff" },
    ],
    keywords: ["reset password", "forgot my password", "locked out"],
  },
  {
    id: "account.details",
    topic: "account",
    title: "Update details",
    say: "You can update your name, mobile, address and preferences in My Account under Personal details.",
    card: { kind: "info", title: "Personal details", body: "Changes apply to future orders straight away.", link: { label: "Open My Account", to: "/account" } },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account.unsubscribe",
    topic: "account",
    title: "Unsubscribe",
    say: "Which messages would you like to stop? You'll still get emails about orders you've bought.",
    card: { kind: "form", form: "unsubscribe", next: "account.unsubscribed" },
    options: [{ label: "Back", next: "account" }],
    keywords: ["unsubscribe", "stop emails", "too many emails", "marketing emails", "stop texts"],
  },
  {
    id: "account.unsubscribed",
    topic: "account",
    title: "Unsubscribed",
    say: "Done — you're unsubscribed from {unsubscribeChannel}. It can take up to 5 business days to fully take effect.",
    card: { kind: "success", title: "Preferences updated", detail: "Unsubscribed from {unsubscribeChannel}" },
    effect: "unsubscribe",
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account.erasure",
    topic: "account",
    title: "Data erasure",
    say: "I can lodge a data erasure request under the Privacy Act. We'll keep records we're legally required to, like tax invoices, and delete the rest.",
    card: { kind: "form", form: "data-erasure", next: "account.erasure.done" },
    options: [{ label: "Back", next: "account" }],
    keywords: ["delete my data", "data erasure", "erase my data", "privacy request", "remove my information"],
  },
  {
    id: "account.erasure.done",
    topic: "account",
    title: "Erasure requested",
    say: "Your data erasure request is lodged with reference {requestRef}. Our Privacy team will confirm by email within 30 days.",
    card: { kind: "success", title: "Privacy request lodged", detail: "Reference {requestRef}" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "account.close",
    topic: "account",
    title: "Close account",
    say: "You can close your account from My Account. Any upcoming tickets stay valid, but you'll need to keep your emailed copies.",
    card: { kind: "info", title: "Close your account", body: "You'll lose access to mobile tickets in the app.", link: { label: "Account settings", to: "/account/close" } },
    options: [{ label: "Thanks", next: "resolved" }],
    keywords: ["close my account", "cancel my account", "delete my account"],
  },
  {
    id: "eventday",
    topic: "eventday",
    title: "Event-day info",
    say: "Which event are you heading to?",
    pick: {
      filter: "attending",
      next: "eventday.info",
      emptySay: "I can't see any upcoming events on this account, but every event page lists gate times and venue info.",
    },
    options: [{ label: "Back to topics", next: "menu" }],
    keywords: ["gates open", "doors open", "what time", "parking", "how do i get there", "venue info", "event day", "getting there", "start time"],
  },
  {
    id: "eventday.info",
    topic: "eventday",
    title: "Your event",
    say: "{orderEvent} is at {orderVenue}, {orderDate}. Gates open at {gatesOpen}. {venueTransport}",
    card: { kind: "event-day" },
    options: [
      { label: "What can I bring?", next: "eventday.bags" },
      { label: "Accessible entry", next: "accessible" },
      { label: "Lost property", next: "eventday.lost" },
      { label: "Thanks", next: "resolved" },
    ],
  },
  {
    id: "eventday.bags",
    topic: "eventday",
    title: "Bag policy",
    say: "{bagPolicy}",
    options: [{ label: "Thanks", next: "resolved" }],
    keywords: ["bag policy", "what can i bring", "bags", "backpack"],
  },
  {
    id: "eventday.lost",
    topic: "eventday",
    title: "Lost property",
    say: "Lost property is handled by the venue. Contact {orderVenue} directly and describe the item, your seat and the event date.",
    options: [{ label: "Thanks", next: "resolved" }],
    keywords: ["lost property", "left my", "lost my"],
  },
  {
    id: "discover.recs",
    topic: "discover",
    title: "Picks for you",
    say: "{recsLine}",
    card: { kind: "recommendations" },
    options: [
      { label: "Back to topics", next: "menu" },
      { label: "That's all, thanks", next: "end" },
    ],
    keywords: ["recommend", "recommendation", "what should i see", "suggest", "something to see", "what's on", "anything good"],
  },
];
