import type { FlowNode } from "./types";

const NOT_LISTED = { label: "My order isn't listed", next: "order.missing" };

export const refundNodes: FlowNode[] = [
  {
    id: "refunds",
    topic: "refunds",
    title: "Refunds & exchanges",
    say: "I can check what's possible for your order. Which one is it about?",
    pick: {
      filter: "active",
      next: "refunds.standard",
      byPolicy: {
        cancelled: "refunds.cancelled",
        rescheduled: "refunds.rescheduled",
        protected: "refunds.protect",
        standard: "refunds.standard",
        refunded: "refunds.already",
      },
      emptySay: "I can't see any orders that could be refunded on this account. If your order was bought with another email, I can help find it.",
    },
    options: [{ label: "Exchange for another date", next: "refunds.exchange" }, NOT_LISTED],
    keywords: ["refund", "refunds", "money back", "can't go", "cant make it", "can't make it", "cannot attend", "cancel my order", "cancel my tickets", "get my money"],
  },
  {
    id: "refunds.cancelled",
    topic: "refunds",
    title: "Cancelled — automatic refund",
    say: "{orderEvent} on {orderShortDate} was cancelled, so you don't need to do a thing. A full refund of {orderTotal}, including fees, goes back to your {cardLabel} automatically within 30 days.",
    card: { kind: "refund", mode: "auto" },
    effect: "refund",
    options: [
      { label: "Great, thanks", next: "resolved" },
      { label: "Find something else to see", next: "discover.recs" },
      { label: "I paid with a gift voucher", next: "refunds.voucher" },
    ],
  },
  {
    id: "refunds.rescheduled",
    topic: "refunds",
    title: "Rescheduled",
    say: "{orderEvent} has moved from {orderOriginalDate} to {orderDate}, and your tickets are valid for the new date. If you can't make it, you can request a full refund until {refundDeadline}.",
    card: { kind: "reschedule" },
    options: [
      { label: "Keep my tickets", next: "refunds.keep" },
      { label: "Request a refund", next: "refunds.rescheduled.confirm" },
    ],
  },
  {
    id: "refunds.rescheduled.confirm",
    topic: "refunds",
    title: "Confirm refund",
    say: "Just to confirm: refund all {orderTickets} tickets for {orderEvent}, {orderTotal}, to your {cardLabel}? The tickets will be cancelled.",
    card: { kind: "order" },
    options: [
      { label: "Yes, refund my tickets", next: "refunds.requested" },
      { label: "No, keep them", next: "refunds.keep" },
    ],
  },
  {
    id: "refunds.requested",
    topic: "refunds",
    title: "Refund requested",
    say: "Done. Your refund of {orderTotal} is on its way to your {cardLabel} and usually lands within 5 to 10 business days. I've emailed the details to {email}.",
    card: { kind: "refund", mode: "requested" },
    effect: "refund",
    options: [
      { label: "Thanks", next: "resolved" },
      { label: "Find something else to see", next: "discover.recs" },
    ],
  },
  {
    id: "refunds.keep",
    topic: "refunds",
    title: "Keeping tickets",
    say: "No worries, your tickets stay valid for {orderDate}. You don't need to do anything.",
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "refunds.protect",
    topic: "refunds",
    title: "Ticket Protect",
    say: "Good news: you added Ticket Protect to this order. If you can't go because of illness, injury, a transport breakdown or another covered reason, you can claim back the ticket price.",
    card: {
      kind: "steps",
      title: "Claiming with Ticket Protect",
      steps: [
        "Have your order number {orderId} and evidence ready, like a medical certificate.",
        "Lodge the claim online before the event, or within 60 days after it.",
        "Approved claims are paid to your nominated account, usually within 10 business days.",
      ],
    },
    options: [
      { label: "Start a claim", next: "refunds.protect.claim" },
      { label: "My reason isn't covered", next: "refunds.standard" },
    ],
    keywords: ["ticket protect", "refund protection", "insurance"],
  },
  {
    id: "refunds.protect.claim",
    topic: "refunds",
    title: "Claim started",
    say: "I've started your Ticket Protect claim for order {orderId} and emailed you a secure link to upload your evidence.",
    card: { kind: "success", title: "Ticket Protect claim started", detail: "Upload link sent to {email}" },
    options: [
      { label: "Thanks", next: "resolved" },
      { label: "Talk to a person", next: "handoff" },
    ],
  },
  {
    id: "refunds.standard",
    topic: "refunds",
    title: "Can't make it",
    say: "{orderEvent} is going ahead as planned, so under Ticketek's purchase policy the tickets can't be refunded for a change of plans. You've still got good options though.",
    card: { kind: "order" },
    options: [
      { label: "Sell on Marketplace", next: "resale.decide" },
      { label: "Transfer to a friend", next: "transfer.decide" },
      { label: "Exchange for another date", next: "refunds.exchange" },
      { label: "Talk to a person", next: "handoff" },
    ],
  },
  {
    id: "refunds.exchange",
    topic: "refunds",
    title: "Exchange tickets",
    say: "Exchanges are only possible when the promoter offers them, for example when extra dates are added. I can pass a request to the team, or you can sell on Marketplace and buy for another date.",
    options: [
      { label: "Request an exchange", next: "handoff" },
      { label: "Sell on Marketplace instead", next: "resale.decide" },
    ],
    keywords: ["exchange", "swap my tickets", "change the date", "different date", "exchange my tickets"],
  },
  {
    id: "refunds.already",
    topic: "refunds",
    title: "Already refunded",
    say: "This order has already been refunded — {orderTotal} is on its way back to your {cardLabel}.",
    card: { kind: "refund", mode: "requested" },
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "refunds.voucher",
    topic: "refunds",
    title: "Voucher refunds",
    say: "Any part paid by gift voucher is refunded as a new voucher, emailed to {email} within 5 business days.",
    options: [{ label: "Thanks", next: "resolved" }],
  },
  {
    id: "changes",
    topic: "changes",
    title: "Event changes",
    say: "Let me check for changes. Which event?",
    pick: {
      filter: "active",
      next: "changes.none",
      byPolicy: { cancelled: "changes.cancelled", rescheduled: "changes.rescheduled", refunded: "refunds.already" },
      emptySay: "I can't see any upcoming events on this account. Cancellations and new dates are always posted on the event page too.",
    },
    options: [NOT_LISTED],
    keywords: ["cancelled", "canceled", "postponed", "rescheduled", "event changes", "date changed", "still going ahead", "still on", "show cancelled"],
  },
  {
    id: "changes.cancelled",
    topic: "changes",
    title: "Event cancelled",
    say: "I'm sorry, {orderEvent} at {orderVenue} on {orderShortDate} has been cancelled. You'll get a full refund automatically, including fees.",
    card: { kind: "order" },
    options: [
      { label: "Tell me about my refund", next: "refunds.cancelled" },
      { label: "Find something else to see", next: "discover.recs" },
    ],
  },
  {
    id: "changes.rescheduled",
    topic: "changes",
    title: "New date",
    say: "{orderEvent} has moved to {orderDate}. Your tickets and seats carry over to the new date automatically.",
    card: { kind: "reschedule" },
    options: [
      { label: "Keep my tickets", next: "refunds.keep" },
      { label: "I can't make the new date", next: "refunds.rescheduled" },
    ],
  },
  {
    id: "changes.none",
    topic: "changes",
    title: "No changes",
    say: "Good news: {orderEvent} is going ahead as planned on {orderDate}. If anything changes, we'll email {email} and update your tickets in the app.",
    card: { kind: "order" },
    options: [
      { label: "The line-up changed", next: "changes.lineup" },
      { label: "Event-day info", next: "eventday.info" },
      { label: "Thanks", next: "resolved" },
    ],
  },
  {
    id: "changes.lineup",
    topic: "changes",
    title: "Line-up changes",
    say: "Support act and set-time changes don't qualify for a refund. If a headline act pulls out, the promoter decides whether refunds are offered and we'll email you.",
    options: [
      { label: "Sell on Marketplace", next: "resale.decide" },
      { label: "Okay, thanks", next: "resolved" },
    ],
    keywords: ["line up", "lineup", "support act", "set times", "headliner"],
  },
];
