import type { FlowNode } from "./types";

export const accountNodes: FlowNode[] = [
  {
    id: "account",
    topic: "account",
    title: "Account & users",
    say: "Sure. What would you like to change on your account?",
    options: [
      { label: "Add a user", next: "account.user" },
      { label: "I can't log in", next: "account.login" },
      { label: "Compare or change my plan", next: "account.plan" },
      { label: "Update billing details", next: "account.billing" },
      { label: "Find my support code", next: "account.code" },
    ],
    keywords: ["account", "my account", "users", "settings", "profile"],
  },
  {
    id: "account.user",
    topic: "account",
    title: "Add a user",
    say: "Who would you like to add? They'll get an email invitation to set a password and turn on two-factor authentication.",
    card: { kind: "form", form: "add-user", next: "account.user.done" },
    options: [{ label: "Back to account", next: "account" }],
    keywords: ["add a user", "new user", "invite a user", "give access", "new staff"],
  },
  {
    id: "account.user.done",
    topic: "account",
    title: "User invited",
    say: "Done. I've invited {newUserName} at {newUserEmail} as {newUserRole}. The invitation is valid for 7 days.",
    card: { kind: "success", title: "Invitation sent", detail: "{newUserName} · {newUserRole} · {newUserEmail}" },
    effect: "add-user",
    options: [
      { label: "Add another user", next: "account.user" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "account.login",
    topic: "account",
    title: "Can't log in",
    say: "Let's get you back in. Is it your password or your two-factor code?",
    options: [
      { label: "Reset my password", next: "account.login.password" },
      { label: "Reset two-factor authentication", next: "account.login.mfa" },
      { label: "My account is locked", next: "handoff" },
    ],
    keywords: ["can't log in", "cant log in", "forgot password", "reset password", "locked out", "two factor", "2fa", "mfa", "authenticator"],
  },
  {
    id: "account.login.password",
    topic: "account",
    title: "Reset password",
    say: "I've sent a password reset link to {email}. It expires in 30 minutes. Check spam if it isn't there in a minute or two.",
    card: { kind: "success", title: "Reset link sent", detail: "Sent to {email} · expires in 30 minutes" },
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "account.login.mfa",
    topic: "account",
    title: "Reset two-factor",
    say: "I've reset two-factor authentication for {email}. Next time you log in, you'll scan a new QR code with your authenticator app.",
    card: { kind: "success", title: "Two-factor reset", detail: "Set up a new authenticator on your next login" },
    effect: "reset-mfa",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "account.plan",
    topic: "account",
    title: "Compare plans",
    say: "You're on {planName}. Here's how the plans compare.",
    card: { kind: "plan-compare" },
    options: [
      { label: "Switch to SiteMinder", next: "account.plan.done", set: { newPlan: "siteminder", newPlanName: "SiteMinder" } },
      { label: "Switch to SiteMinder Plus", next: "account.plan.done", set: { newPlan: "plus", newPlanName: "SiteMinder Plus" } },
      { label: "Talk to sales about Groups & Chains", next: "handoff" },
      { label: "Keep my plan", next: "resolved" },
    ],
    keywords: ["plan", "change plan", "upgrade", "downgrade", "compare plans", "pricing plan"],
  },
  {
    id: "account.plan.done",
    topic: "account",
    title: "Plan changed",
    say: "Done. You're moving to {newPlanName} from your next billing date. Everything you've set up stays as it is.",
    card: { kind: "success", title: "Plan updated", detail: "{newPlanName} from your next billing date" },
    effect: "change-plan",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "account.billing",
    topic: "account",
    title: "Billing details",
    say: "Here are the billing details on file. Update anything that's changed.",
    card: { kind: "form", form: "billing-details", next: "account.billing.done" },
    options: [{ label: "Back to account", next: "account" }],
    keywords: ["billing details", "billing email", "abn", "tax details", "invoice email", "company details"],
  },
  {
    id: "account.billing.done",
    topic: "account",
    title: "Details updated",
    say: "Updated. Invoices will go to {billingEmail} with ABN {billingAbn} from now on.",
    card: { kind: "success", title: "Billing details saved", detail: "{billingEmail} · ABN {billingAbn}" },
    effect: "billing-details",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "account.code",
    topic: "account",
    title: "Support code",
    say: "Your support code is {supportCode}. Quote it when you call us so we can find {propertyName} straight away. You can generate a new one any time under Help in the platform.",
    card: { kind: "info", title: "Support code {supportCode}", body: "Valid for 24 hours. It lets our team find your property without asking for your password.", link: { label: "Open Help", to: "/app/help" } },
    options: [
      { label: "Call support", next: "handoff.call" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
];
