import type { FlowNode } from "./types";

export const arrangementNodes: FlowNode[] = [
  {
    id: "arrangements",
    topic: "arrangements",
    title: "Payment support",
    say: "Thanks for letting us know — quiet seasons happen. Which invoice is it?",
    pick: {
      filter: "invoices-unpaid",
      next: "arrangements.options",
      emptySay: "Log in and I'll see what's due and what we can offer.",
    },
    options: [{ label: "Talk to someone about my situation", next: "arrangements.hardship" }],
    keywords: [
      "more time to pay",
      "can't pay",
      "cant pay",
      "payment plan",
      "struggling to pay",
      "extension",
    ],
  },
  {
    id: "arrangements.options",
    topic: "arrangements",
    title: "Your options",
    say: "Invoice {invoiceId} is {invoiceTotal}, due {invoiceDue}. I can give you 14 more days, split it into instalments, or talk about a seasonal pause.",
    card: { kind: "invoice" },
    picker: "arrangements",
    options: [
      { label: "14 more days", next: "arrangements.extension" },
      { label: "Pay in instalments", next: "arrangements.instalment" },
      { label: "Pause for the off-season", next: "arrangements.pause" },
      { label: "Talk to someone", next: "arrangements.hardship" },
    ],
  },
  {
    id: "arrangements.extension",
    topic: "arrangements",
    title: "Payment extension",
    say: "I can move {invoiceId} out by 14 days, with no late fee and no change to your service. Shall I set that up?",
    card: { kind: "extension" },
    picker: "arrangements",
    options: [
      { label: "Yes, extend it", next: "arrangements.extension.done" },
      { label: "Show other options", next: "arrangements.options" },
    ],
  },
  {
    id: "arrangements.extension.done",
    topic: "arrangements",
    title: "Extension agreed",
    say: "Done. Invoice {invoiceId} for {invoiceTotal} is now due {invoiceExtendedDue}. Your channels and booking engine keep running as normal.",
    card: {
      kind: "success",
      title: "Extension agreed",
      detail: "{invoiceId} · {invoiceTotal} · now due {invoiceExtendedDue}",
    },
    effect: "extension",
    picker: "arrangements",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "arrangements.instalment",
    topic: "arrangements",
    title: "Instalment plan",
    say: "I can split {invoiceTotal} into three monthly payments of {instalmentAmount}, taken from your {cardLabel}. Want to go ahead?",
    card: { kind: "instalment" },
    picker: "arrangements",
    options: [
      { label: "Yes, set up instalments", next: "arrangements.instalment.done" },
      { label: "Show other options", next: "arrangements.options" },
    ],
    keywords: ["instalments", "installments", "split the payment", "pay in parts"],
  },
  {
    id: "arrangements.instalment.done",
    topic: "arrangements",
    title: "Instalments set up",
    say: "All set. You'll pay {instalmentAmount} a month for three months, starting on the original due date. I've emailed the schedule to {billingEmail}.",
    card: {
      kind: "success",
      title: "Instalment plan active",
      detail: "3 × {instalmentAmount} · schedule sent to {billingEmail}",
    },
    effect: "instalment",
    picker: "arrangements",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "arrangements.pause",
    topic: "arrangements",
    title: "Seasonal pause",
    say: "Seasonal properties can pause SiteMinder for up to three months a year. Channels close, your setup stays saved, and you only pay a small hold fee. Our Customer Success team sets this up with you.",
    card: {
      kind: "info",
      title: "Seasonal pause",
      body: "Up to 3 months a year. Availability closes on every channel, your mappings and rates stay saved, and reactivation takes minutes.",
    },
    options: [
      { label: "Talk to Customer Success", next: "handoff" },
      { label: "Not now, thanks", next: "resolved" },
    ],
    keywords: [
      "pause my account",
      "off season",
      "seasonal pause",
      "closing for winter",
      "hibernate",
    ],
  },
  {
    id: "arrangements.hardship",
    topic: "arrangements",
    title: "Financial difficulty",
    say: "I'm sorry things are tough. Our Customer Success team can look at your whole situation, including plan changes and longer arrangements, and nothing gets switched off while we talk.",
    card: {
      kind: "info",
      title: "We're here to help",
      body: "Tell us what's going on and we'll work out an arrangement that keeps your property selling.",
    },
    options: [
      { label: "Talk to Customer Success", next: "handoff" },
      { label: "Back to payment options", next: "arrangements" },
    ],
    keywords: ["financial difficulty", "hardship", "cash flow", "going under", "can't afford"],
  },
];
