import type { FlowNode } from "./types";

export const billingNodes: FlowNode[] = [
  {
    id: "billing",
    topic: "billing",
    title: "Billing & subscription",
    say: "Sure, let's look at your SiteMinder billing. What do you need?",
    options: [
      { label: "Pay an invoice", next: "billing.pay" },
      { label: "My invoice is higher than expected", next: "billing.high" },
      { label: "Understand my invoice", next: "billing.understand" },
      { label: "Set up direct debit", next: "billing.directdebit" },
      { label: "Refund my account credit", next: "billing.refund" },
      { label: "I need more time to pay", next: "arrangements" },
    ],
    keywords: [
      "bill",
      "billing",
      "invoice",
      "invoices",
      "subscription fee",
      "how much do i owe",
      "account balance",
    ],
  },
  {
    id: "billing.pay",
    topic: "billing",
    title: "Pay an invoice",
    say: "Which invoice would you like to pay?",
    pick: {
      filter: "invoices-unpaid",
      next: "billing.pay.method",
      emptySay: "Log in and I'll show you what's due. If everything's paid, you're all square.",
    },
    options: [{ label: "Back to billing", next: "billing" }],
    keywords: [
      "pay my invoice",
      "pay invoice",
      "make a payment",
      "pay now",
      "pay the bill",
      "pay my bill",
    ],
  },
  {
    id: "billing.pay.method",
    topic: "billing",
    title: "How to pay",
    say: "Invoice {invoiceId} for {invoicePeriod} is {invoiceTotal}, due {invoiceDue}. How would you like to pay?",
    card: { kind: "invoice" },
    picker: "billing.pay",
    options: [
      { label: "Pay now with my {cardLabel}", next: "billing.pay.card" },
      { label: "Show bank transfer details", next: "billing.pay.bank" },
      { label: "Other ways to pay", next: "billing.pay.other" },
      { label: "I can't pay it all right now", next: "arrangements" },
    ],
  },
  {
    id: "billing.pay.card",
    topic: "billing",
    title: "Pay with saved card",
    say: "I'll charge {invoiceTotal} to your {cardLabel} for invoice {invoiceId}. Shall I go ahead?",
    card: { kind: "payment-confirm" },
    picker: "billing.pay",
    options: [
      { label: "Yes, pay {invoiceTotal}", next: "billing.pay.done" },
      { label: "Not now", next: "billing" },
    ],
    keywords: ["saved card", "pay with card", "credit card", "visa", "mastercard"],
  },
  {
    id: "billing.pay.done",
    topic: "billing",
    title: "Payment made",
    say: "Done. {invoiceTotal} has been paid on your {cardLabel} and your receipt number is {receipt}. Invoice {invoiceId} now shows as paid in Billing.",
    card: {
      kind: "success",
      title: "Payment successful",
      detail: "{invoiceTotal} paid with {cardLabel} · Receipt {receipt}",
    },
    effect: "pay-invoice",
    picker: "billing.pay",
    options: [
      { label: "Set up direct debit so I don't forget", next: "billing.directdebit" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "billing.pay.bank",
    topic: "billing",
    title: "Bank transfer details",
    say: "Here are the bank transfer details. Use {invoiceId} as the reference so we can match your payment — it takes one to two business days to clear.",
    card: { kind: "bank-transfer" },
    picker: "billing.pay",
    options: [
      { label: "Pay by card instead", next: "billing.pay.card" },
      { label: "That's all, thanks", next: "resolved" },
    ],
    keywords: ["bank transfer", "eft", "bank details", "bsb", "wire transfer"],
  },
  {
    id: "billing.pay.other",
    topic: "billing",
    title: "Other ways to pay",
    say: "You can pay any invoice from Billing in the platform, or set up direct debit so invoices are paid automatically on the due date.",
    card: {
      kind: "steps",
      title: "Ways to pay SiteMinder",
      steps: [
        "Card payment in Billing › Invoices",
        "Bank transfer using the invoice number as reference",
        "Direct debit from your bank account or card",
        "Annual prepayment for a discount — ask your account manager",
      ],
    },
    options: [
      { label: "Set up direct debit", next: "billing.directdebit" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "billing.high",
    topic: "billing",
    title: "Higher than expected",
    say: "Which invoice looks higher than you expected?",
    pick: {
      filter: "invoices-all",
      next: "billing.high.check",
      emptySay: "Log in and I'll compare your invoices month by month.",
    },
    options: [{ label: "Back to billing", next: "billing" }],
    keywords: [
      "higher than expected",
      "invoice is high",
      "bill is high",
      "invoice went up",
      "why is my invoice",
      "charged more",
    ],
  },
  {
    id: "billing.high.check",
    topic: "billing",
    title: "Checking invoice",
    say: "",
    decide: {
      fact: "invoiceDriver",
      cases: { bookings: "billing.high.bookings", addon: "billing.high.addon" },
      otherwise: "billing.high.unchanged",
    },
    options: [],
  },
  {
    id: "billing.high.bookings",
    topic: "billing",
    title: "More bookings",
    say: "{invoicePeriod} came to {invoiceTotal}, {invoiceDelta} on the month before. Your subscription didn't change — you took more direct bookings, so Booking Engine and SiteMinder Pay fees rose with them.",
    card: { kind: "invoice-compare" },
    picker: "billing.high",
    options: [
      { label: "Explain the fees", next: "billing.understand.fees" },
      { label: "Pay this invoice", next: "billing.pay.method" },
      { label: "That makes sense", next: "resolved" },
    ],
  },
  {
    id: "billing.high.addon",
    topic: "billing",
    title: "New add-on",
    say: "{invoicePeriod} came to {invoiceTotal}, {invoiceDelta} on the month before. Most of that is Demand Plus, which started this month, plus higher Booking Engine fees from more direct bookings.",
    card: { kind: "invoice-compare" },
    picker: "billing.high",
    options: [
      { label: "What is Demand Plus?", next: "grow.demandplus" },
      { label: "I didn't sign up for that", next: "handoff" },
      { label: "That makes sense", next: "resolved" },
    ],
  },
  {
    id: "billing.high.unchanged",
    topic: "billing",
    title: "Nothing changed",
    say: "{invoicePeriod} came to {invoiceTotal}, in line with the month before. If it still looks wrong, our billing team can go through it line by line with you.",
    card: { kind: "invoice-compare" },
    picker: "billing.high",
    options: [
      { label: "Talk to the billing team", next: "handoff" },
      { label: "That's fine, thanks", next: "resolved" },
    ],
  },
  {
    id: "billing.understand",
    topic: "billing",
    title: "Understand my invoice",
    say: "Your SiteMinder invoice has a fixed subscription and usage-based fees. Here's what each part means.",
    card: {
      kind: "steps",
      title: "Reading your invoice",
      steps: [
        "Subscription — your {planName} plan, billed monthly in advance",
        "Add-ons — products like Demand Plus or Dynamic Revenue Plus",
        "Booking Engine fees — a small fee per direct booking",
        "SiteMinder Pay — card processing on payments you collect",
      ],
    },
    options: [
      { label: "Explain the usage fees", next: "billing.understand.fees" },
      { label: "Compare with last month", next: "billing.high" },
      { label: "That's clear, thanks", next: "resolved" },
    ],
    keywords: ["understand my invoice", "explain my invoice", "what is this charge", "line items"],
  },
  {
    id: "billing.understand.fees",
    topic: "billing",
    title: "Usage fees",
    say: "Usage fees only apply when you earn: a per-booking fee on Booking Engine reservations and card processing on SiteMinder Pay. OTA bookings never attract a SiteMinder fee.",
    card: {
      kind: "info",
      title: "Why usage fees move",
      body: "More direct bookings or more card payments through SiteMinder Pay mean higher usage fees — but each one is a booking with no OTA commission.",
      link: { label: "See pricing", to: "/pricing" },
    },
    options: [{ label: "That's clear, thanks", next: "resolved" }],
  },
  {
    id: "billing.directdebit",
    topic: "billing",
    title: "Direct debit",
    say: "With direct debit, each invoice is paid automatically on its due date from your {cardLabel}. You'll still get the invoice by email first. Switch it on?",
    options: [
      { label: "Yes, switch on direct debit", next: "billing.directdebit.done" },
      { label: "Not now", next: "billing" },
    ],
    keywords: ["direct debit", "automatic payments", "auto pay", "autopay"],
  },
  {
    id: "billing.directdebit.done",
    topic: "billing",
    title: "Direct debit on",
    say: "All set. Direct debit is on, and future invoices will be paid from your {cardLabel} on their due date.",
    card: {
      kind: "success",
      title: "Direct debit active",
      detail: "Paid on each due date from your {cardLabel}",
    },
    effect: "direct-debit",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "billing.refund",
    topic: "billing",
    title: "Account credit refund",
    say: "You have {creditAmount} in credit on your account. I can refund it to your {cardLabel} or leave it to come off your next invoice.",
    card: { kind: "credit-refund" },
    options: [
      { label: "Refund {creditAmount}", next: "billing.refund.done" },
      { label: "Keep it for my next invoice", next: "resolved" },
    ],
    keywords: ["refund", "credit refund", "account credit", "overpaid", "money back"],
  },
  {
    id: "billing.refund.done",
    topic: "billing",
    title: "Refund requested",
    say: "Done. {creditAmount} is on its way back to your {cardLabel} and should arrive in three to five business days.",
    card: {
      kind: "success",
      title: "Refund on its way",
      detail: "{creditAmount} to your {cardLabel} · 3–5 business days",
    },
    effect: "credit-refund",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
];
