import type { FlowNode } from "./types";

export const channelNodes: FlowNode[] = [
  {
    id: "channels",
    topic: "channels",
    title: "Channels & connectivity",
    say: "Let's check your channels. Which one needs attention? {channelIssueLine}",
    pick: {
      filter: "channels-all",
      next: "channels.healthy",
      byStatus: {
        "mapping-error": "channels.mapping",
        "auth-failed": "channels.auth",
        paused: "channels.paused",
      },
      emptySay: "Log in and I can check every channel you're connected to.",
    },
    options: [
      { label: "Is SiteMinder having an outage?", next: "channels.status" },
      { label: "Connect a new channel", next: "channels.add" },
      { label: "Rooms are selling that shouldn't", next: "channels.stopsell" },
    ],
    keywords: [
      "channel",
      "channels",
      "channel manager",
      "ota",
      "connectivity",
      "not syncing",
      "sync",
      "mapping",
      "booking.com",
      "expedia",
      "airbnb",
      "agoda",
      "trip.com",
    ],
  },
  {
    id: "channels.mapping",
    topic: "channels",
    title: "Mapping error",
    say: "{channelName} has a mapping error on {channelIssueRoom}: that room exists in SiteMinder but isn't linked to a room on {channelName}, so it hasn't had availability or rates since {channelLastSync}. I can re-map it to the matching room now.",
    card: { kind: "channel" },
    options: [
      { label: "Yes, fix the mapping", next: "channels.mapping.done" },
      { label: "Show me how to do it myself", next: "channels.mapping.steps" },
      { label: "Talk to a connectivity specialist", next: "handoff" },
    ],
    keywords: ["mapping error", "room not mapped", "unmapped", "map a room", "mapping"],
  },
  {
    id: "channels.mapping.steps",
    topic: "channels",
    title: "Map rooms yourself",
    say: "Here's how to map it in the platform. It takes about two minutes, and SiteMinder pushes a full update as soon as you save.",
    card: {
      kind: "steps",
      title: "Edit room rates mapping",
      steps: [
        "Go to Distribution › Channels › My channels",
        "Find {channelName} and choose Edit room rates mapping",
        "Link {channelIssueRoom} to the matching room and rate plan on {channelName}",
        "Save — a full availability and rate update is sent automatically",
      ],
    },
    options: [
      { label: "Do it for me instead", next: "channels.mapping.done" },
      { label: "That fixed it", next: "resolved" },
    ],
  },
  {
    id: "channels.mapping.done",
    topic: "channels",
    title: "Mapping fixed",
    say: "Done. {channelIssueRoom} is mapped to {channelName} again and I've sent a full availability and rate update for the next 365 days. It can take up to 15 minutes to show on the {channelName} extranet.",
    card: {
      kind: "success",
      title: "Mapping restored",
      detail: "{channelName} · {channelIssueRoom} · full update queued",
    },
    effect: "fix-mapping",
    options: [
      { label: "Check my other channels", next: "channels" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "channels.auth",
    topic: "channels",
    title: "Credentials expired",
    say: "{channelName} stopped accepting SiteMinder's connection on {channelLastSync}, usually because the connection was revoked or the listing was re-linked on their side. Re-authorise SiteMinder in {channelName}, then confirm your listing ID here and I'll reconnect.",
    card: { kind: "channel" },
    options: [
      { label: "Reconnect {channelName}", next: "channels.auth.form" },
      { label: "Talk to a connectivity specialist", next: "handoff" },
    ],
    keywords: [
      "credentials",
      "authentication failed",
      "auth failed",
      "disconnected",
      "reconnect",
      "revoked",
      "password changed",
    ],
  },
  {
    id: "channels.auth.form",
    topic: "channels",
    title: "Reconnect channel",
    say: "Enter your {channelName} listing or property ID. Never share your {channelName} password — SiteMinder doesn't need it.",
    card: { kind: "form", form: "channel-credentials", next: "channels.auth.done" },
    options: [{ label: "Back", next: "channels.auth" }],
  },
  {
    id: "channels.auth.done",
    topic: "channels",
    title: "Channel reconnected",
    say: "{channelName} is connected again on listing {credListingId}. I've pushed a full update, and any bookings made while it was disconnected will download in the next few minutes.",
    card: {
      kind: "success",
      title: "Reconnected",
      detail: "{channelName} · listing {credListingId} · bookings re-syncing",
    },
    effect: "reconnect-channel",
    options: [
      { label: "Check my other channels", next: "channels" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "channels.paused",
    topic: "channels",
    title: "Channel paused",
    say: "{channelName} is paused, so it isn't receiving availability or sending bookings. Would you like to switch it back on?",
    card: { kind: "channel" },
    options: [
      { label: "Yes, resume {channelName}", next: "channels.paused.done" },
      { label: "Keep it paused", next: "resolved" },
    ],
    keywords: ["paused", "resume channel", "turn channel on", "switch channel back on"],
  },
  {
    id: "channels.paused.done",
    topic: "channels",
    title: "Channel resumed",
    say: "{channelName} is live again. I've sent your current availability and rates, so it'll start taking bookings within 15 minutes.",
    card: { kind: "success", title: "Channel resumed", detail: "{channelName} is selling again" },
    effect: "resume-channel",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "channels.healthy",
    topic: "channels",
    title: "Channel looks healthy",
    say: "{channelName} is connected and last synced {channelLastSync}. Let me run a live sync test so we can see exactly what it's receiving.",
    card: { kind: "sync-test" },
    options: [
      { label: "Rates on {channelName} still look wrong", next: "channels.healthy.delay" },
      { label: "Looks right now, thanks", next: "resolved" },
    ],
    keywords: ["sync test", "test connection", "check connection"],
  },
  {
    id: "channels.healthy.delay",
    topic: "channels",
    title: "Still looks wrong",
    say: "If the sync test passed, SiteMinder has delivered the update and {channelName} is still processing it, or a rule on their side is overriding it. Check these before we escalate.",
    card: {
      kind: "steps",
      title: "Before we escalate",
      steps: [
        "Wait 15 minutes — some channels queue updates at busy times",
        "Check {channelName} hasn't applied its own promotion or member discount",
        "Make sure the rate plan isn't derived from another plan in the extranet",
        "Clear cache or check in a private window as a guest would",
      ],
    },
    options: [
      { label: "Still wrong — talk to a specialist", next: "handoff" },
      { label: "That explains it", next: "resolved" },
    ],
  },
  {
    id: "channels.status",
    topic: "channels",
    title: "Platform status",
    say: "{statusLine}",
    card: { kind: "platform-status" },
    options: [
      { label: "It's just my property", next: "channels" },
      { label: "Talk to a person", next: "handoff" },
    ],
    keywords: ["outage", "is siteminder down", "platform status", "system status", "status page"],
  },
  {
    id: "channels.add",
    topic: "channels",
    title: "Connect a channel",
    say: "SiteMinder connects to more than 450 channels. Here's how to add one — most go live the same day.",
    card: {
      kind: "steps",
      title: "Connect a new channel",
      steps: [
        "Go to Distribution › Channels › Add channel",
        "Search for the channel and choose Connect",
        "Enter the property ID the channel gave you and authorise SiteMinder in their extranet",
        "Map your room types and rate plans, then switch the channel on",
      ],
    },
    options: [
      { label: "Which channels should I add?", next: "grow.demandplus" },
      { label: "That's all, thanks", next: "resolved" },
    ],
    keywords: ["add a channel", "connect a channel", "new channel", "new ota"],
  },
  {
    id: "channels.stopsell",
    topic: "channels",
    title: "Selling when closed",
    say: "If a closed room is still selling, the channel usually has availability you loaded directly in its extranet, outside SiteMinder. Let's isolate it.",
    card: {
      kind: "steps",
      title: "Find the leak",
      steps: [
        "Check the booking's channel in Reservations — it shows where it came from",
        "On that channel, look for allotments or free-sale loaded in the extranet",
        "Remove extranet-loaded inventory so SiteMinder is the only source",
        "Use a stop sell in Rates & availability to close the room everywhere at once",
      ],
    },
    options: [
      { label: "I've been overbooked", next: "urgent.overbooking" },
      { label: "Talk to a connectivity specialist", next: "handoff" },
      { label: "That's all, thanks", next: "resolved" },
    ],
    keywords: [
      "stop sell not working",
      "selling when closed",
      "closed but selling",
      "extranet allotment",
    ],
  },
];
