import type { FlowNode } from "./types";

export const reservationNodes: FlowNode[] = [
  {
    id: "reservations",
    topic: "reservations",
    title: "Reservations",
    say: "Which booking is this about? I've put the ones that need attention first.",
    pick: {
      filter: "bookings-issues",
      next: "reservations.ok",
      byStatus: {
        "missing-in-pms": "reservations.missing",
        modified: "reservations.modified",
        cancelled: "reservations.cancelled",
        "card-declined": "reservations.card",
        overbooked: "urgent.overbooking",
      },
      emptySay: "Log in and I'll pull up your recent bookings.",
    },
    options: [
      { label: "Find another booking", next: "reservations.lookup" },
      { label: "Bookings aren't reaching my PMS at all", next: "reservations.pms" },
    ],
    keywords: [
      "booking",
      "reservation",
      "reservations",
      "booking missing",
      "missing booking",
      "isn't in my pms",
      "not in my pms",
      "guest booking",
    ],
  },
  {
    id: "reservations.lookup",
    topic: "reservations",
    title: "Upcoming bookings",
    say: "Here are your next arrivals. Pick the one you mean.",
    pick: {
      filter: "bookings-upcoming",
      next: "reservations.ok",
      byStatus: {
        "missing-in-pms": "reservations.missing",
        modified: "reservations.modified",
        cancelled: "reservations.cancelled",
        "card-declined": "reservations.card",
        overbooked: "urgent.overbooking",
      },
      emptySay: "Log in and I'll pull up your upcoming arrivals.",
    },
    options: [{ label: "It isn't listed", next: "record.missing" }],
    keywords: ["find a booking", "look up a booking", "booking reference", "upcoming arrivals"],
  },
  {
    id: "reservations.ok",
    topic: "reservations",
    title: "Booking details",
    say: "{bookingGuest}'s booking from {bookingChannel} is confirmed: {bookingRoom}, arriving {bookingCheckIn} for {bookingNights}. It's in SiteMinder and was delivered to {pms}. What do you need to do with it?",
    card: { kind: "booking" },
    options: [
      { label: "It's not showing in {pms}", next: "reservations.missing" },
      { label: "Close this room for that date", next: "reservations.closeout" },
      { label: "All good, thanks", next: "resolved" },
    ],
  },
  {
    id: "reservations.missing",
    topic: "reservations",
    title: "Not in PMS",
    say: "{bookingGuest}'s {bookingChannel} booking {bookingId} reached SiteMinder, but {pms} didn't acknowledge it. That's usually a room or rate code {pms} doesn't recognise. I can resend it now.",
    card: { kind: "booking" },
    options: [
      { label: "Resend to {pms}", next: "reservations.missing.done" },
      { label: "Check bookings aren't failing for everyone", next: "reservations.pms" },
      { label: "Talk to a person", next: "handoff" },
    ],
    keywords: ["resend booking", "booking didn't come through", "pms missing booking"],
  },
  {
    id: "reservations.missing.done",
    topic: "reservations",
    title: "Booking resent",
    say: "Resent. {pms} has acknowledged {bookingId} for {bookingGuest}, and it's now confirmed in both systems. If the room code was the problem, I've flagged it so future bookings map correctly.",
    card: {
      kind: "success",
      title: "Delivered to {pms}",
      detail: "{bookingId} · {bookingGuest} · {bookingRoom}",
    },
    effect: "resend-booking",
    options: [
      { label: "Check another booking", next: "reservations" },
      { label: "That's all, thanks", next: "resolved" },
    ],
  },
  {
    id: "reservations.pms",
    topic: "reservations",
    title: "PMS connection",
    say: "Your PMS connection to {pms} is healthy and has taken bookings in the last hour, so this isn't affecting everyone. If several bookings are missing, check these first.",
    card: {
      kind: "steps",
      title: "Check the {pms} connection",
      steps: [
        "In {pms}, confirm the SiteMinder interface is switched on",
        "Make sure every room type and rate plan in SiteMinder has a matching {pms} code",
        "Look for bookings parked in {pms}'s interface error queue",
        "Use Resend in SiteMinder Reservations for anything missing",
      ],
    },
    options: [
      { label: "Talk to a person", next: "handoff" },
      { label: "That's all, thanks", next: "resolved" },
    ],
    keywords: [
      "pms not receiving",
      "pms connection",
      "pms interface",
      "mews",
      "cloudbeds",
      "opera",
    ],
  },
  {
    id: "reservations.modified",
    topic: "reservations",
    title: "Modified booking",
    say: "{bookingGuest} changed their {bookingChannel} booking: {bookingChange}. SiteMinder sent the update to {pms}, and the stay is now {bookingNights} for {bookingTotal}.",
    card: { kind: "booking" },
    options: [
      { label: "The change didn't reach {pms}", next: "reservations.missing" },
      { label: "Got it, thanks", next: "resolved" },
    ],
    keywords: ["modified booking", "booking changed", "modification", "guest changed dates"],
  },
  {
    id: "reservations.cancelled",
    topic: "reservations",
    title: "Cancelled booking",
    say: "{bookingGuest} cancelled their {bookingChannel} booking for {bookingCheckIn}. The room went back on sale everywhere straight away. Any cancellation fee is charged by {bookingChannel} under its own policy.",
    card: { kind: "booking" },
    options: [
      { label: "Why wasn't a fee charged?", next: "reservations.cancelled.fees" },
      { label: "Got it, thanks", next: "resolved" },
    ],
    keywords: ["cancelled booking", "cancellation", "guest cancelled", "no show"],
  },
  {
    id: "reservations.cancelled.fees",
    topic: "reservations",
    title: "Cancellation fees",
    say: "OTA bookings follow the channel's policy and the channel collects any fee. For direct bookings, SiteMinder Pay can charge the guest's stored card under your own policy.",
    card: {
      kind: "info",
      title: "Who charges the fee?",
      body: "OTAs (Booking.com, Expedia and others) apply and collect their own cancellation fees. Direct and Booking Engine reservations use the policy on your rate plan, and SiteMinder Pay can charge the saved card for you.",
      link: { label: "Open Reservations", to: "/app/reservations" },
    },
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "reservations.card",
    topic: "reservations",
    title: "Card declined",
    say: "The card on {bookingGuest}'s {bookingId} booking was declined for the {bookingTotal} deposit. I can retry it through SiteMinder Pay now, or email the guest a secure link to update their card.",
    card: { kind: "booking" },
    options: [
      { label: "Retry the card", next: "reservations.card.done" },
      { label: "Email the guest a payment link", next: "reservations.card.link" },
      { label: "Talk to a person", next: "handoff" },
    ],
    keywords: ["card declined", "declined card", "payment failed", "virtual card", "invalid card"],
  },
  {
    id: "reservations.card.done",
    topic: "reservations",
    title: "Card charged",
    say: "That worked — {bookingTotal} has been charged through SiteMinder Pay and {bookingGuest}'s booking is confirmed.",
    card: {
      kind: "success",
      title: "Payment captured",
      detail: "{bookingTotal} · {bookingId} · SiteMinder Pay",
    },
    effect: "retry-card",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "reservations.card.link",
    topic: "reservations",
    title: "Payment link sent",
    say: "I've emailed {bookingGuest} a secure link to update their card. It stays valid for 48 hours, and you'll see the booking turn green once they've paid.",
    card: {
      kind: "success",
      title: "Payment link sent",
      detail: "Secure link emailed to {bookingGuest} · expires in 48 hours",
    },
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
  {
    id: "reservations.closeout",
    topic: "reservations",
    title: "Close a room",
    say: "I'll put a stop sell on {bookingRoom} for {bookingCheckIn} on every channel. Bookings already made aren't affected. Go ahead?",
    card: { kind: "booking" },
    options: [
      { label: "Yes, close it", next: "reservations.closeout.done" },
      { label: "No, leave it open", next: "resolved" },
    ],
  },
  {
    id: "reservations.closeout.done",
    topic: "reservations",
    title: "Room closed",
    say: "Done. {bookingRoom} is closed on {bookingCheckIn} across all your channels. You can reopen it any time in Rates & availability.",
    card: {
      kind: "success",
      title: "Stop sell applied",
      detail: "{bookingRoom} · {bookingCheckIn} · all channels",
    },
    effect: "close-out",
    options: [{ label: "That's all, thanks", next: "resolved" }],
  },
];
