import {
  Accessibility,
  Blocks,
  BookOpenText,
  Briefcase,
  ChartBar,
  ChartLine,
  ClipboardList,
  Compass,
  Database,
  FlaskConical,
  GraduationCap,
  Hammer,
  Handshake,
  HeartPulse,
  Images,
  Landmark,
  LayoutDashboard,
  LayoutTemplate,
  Layers,
  Lightbulb,
  Mail,
  Map,
  MessageSquareText,
  Minimize2,
  MonitorPlay,
  PanelsTopLeft,
  PenLine,
  Plug,
  Rocket,
  Search,
  ServerCog,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  UserRound,
  UsersRound,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  Accessibility,
  Blocks,
  BookOpenText,
  Briefcase,
  ChartBar,
  ChartLine,
  ClipboardList,
  Compass,
  Database,
  FlaskConical,
  GraduationCap,
  Hammer,
  Handshake,
  HeartPulse,
  Images,
  Landmark,
  LayoutDashboard,
  LayoutTemplate,
  Layers,
  Lightbulb,
  Mail,
  Map,
  MessageSquareText,
  Minimize2,
  MonitorPlay,
  PanelsTopLeft,
  PenLine,
  Plug,
  Rocket,
  Search,
  ServerCog,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  UserRound,
  UsersRound,
  Workflow,
  Zap,
};

interface IconProps {
  name: string;
  className?: string;
}

/** Resolve a lucide icon by name (used by data-driven pages). */
export function Icon({ name, className }: IconProps) {
  const Cmp = registry[name] ?? Sparkles;
  return <Cmp className={className} aria-hidden />;
}
